IMPORTAR LIBRERIAS

In [26]:
import pandas as pd
import numpy as np

print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [27]:
import os

os.listdir("../data/raw")

['API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_285.csv',
 'API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_57.csv',
 'API_SL.UEM.TOTL.ZS_DS2_es_csv_v2_7203.csv']

In [28]:
import pandas as pd

pib = pd.read_csv(
    "../data/raw/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_57.csv",
    skiprows=4
)

inflacion = pd.read_csv(
    "../data/raw/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_285.csv",
    skiprows=4
)

interes = pd.read_csv(
    "../data/raw/API_SL.UEM.TOTL.ZS_DS2_es_csv_v2_7203.csv",
    skiprows=4
)

print("Archivos cargados correctamente")

Archivos cargados correctamente

LIMPIEZA DEL PIB

In [29]:
pib.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.493430,3.212471,1.229144,-23.940059,14.833692,10.607961,9.516360,6.810777,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.418605,7.937089,5.624317,4.650349,5.138153,...,2.678863,2.706207,1.935593,-2.930764,4.452643,3.668029,1.941382,2.787931,3.743016,NaN
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,1.873193,NaN,NaN
3,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.869593,3.726016,7.038172,5.364580,4.105660,...,2.302761,2.899954,3.283142,-3.718793,2.545473,4.477108,3.644591,4.596183,4.600100,NaN
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.164689,-0.506698,-1.055234,-5.273491,1.090584,3.557492,1.320166,4.952679,3.133535,NaN

UNA SOLA FILA

In [30]:
# Seleccionar únicamente Ecuador

pib_ecuador = pib[pib["Country Code"] == "ECU"]

pib_ecuador

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
66,Ecuador,ECU,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,5.124415,4.919147,2.106368,7.407245,3.275082,...,5.970399,1.044295,0.165404,-9.245096,9.421893,5.868424,1.832841,-1.94409,3.725949,NaN

TRANSFORMAR EN AÑOS

In [31]:
# Eliminar columnas que no necesitamos

pib_ecuador = pib_ecuador.drop(
    columns=["Country Name", "Country Code", "Indicator Name", "Indicator Code", "Unnamed: 70"],
    errors="ignore"
)

pib_ecuador

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
66,NaN,5.124415,4.919147,2.106368,7.407245,3.275082,-0.339526,4.621074,1.909438,4.669238,...,-0.687954,5.970399,1.044295,0.165404,-9.245096,9.421893,5.868424,1.832841,-1.94409,3.725949

TRANSFORMAR

In [32]:
pib_final = pib_ecuador.T

pib_final.head()

            66
1960       NaN
1961  5.124415
1962  4.919147
1963  2.106368
1964  7.407245

In [33]:
pib_ecuador

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
66,NaN,5.124415,4.919147,2.106368,7.407245,3.275082,-0.339526,4.621074,1.909438,4.669238,...,-0.687954,5.970399,1.044295,0.165404,-9.245096,9.421893,5.868424,1.832841,-1.94409,3.725949

LIMPIEZA DE INFLACION

In [34]:
inflacion_ecuador = inflacion[inflacion["Country Code"] == "ECU"]

inflacion_ecuador

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
66,Ecuador,ECU,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.676599,3.985621,2.870885,5.939509,4.034205,3.069071,...,0.417336,-0.224103,0.266013,-0.338872,0.133251,3.46617,2.215688,1.547325,0.710469,NaN

In [35]:
inflacion_ecuador = inflacion_ecuador.drop(
    columns=["Country Name", "Country Code", "Indicator Name", "Indicator Code", "Unnamed: 70"],
    errors="ignore"
)

inflacion_ecuador

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
66,1.676599,3.985621,2.870885,5.939509,4.034205,3.069071,5.453727,3.818138,4.317656,6.326681,...,1.728265,0.417336,-0.224103,0.266013,-0.338872,0.133251,3.46617,2.215688,1.547325,0.710469

In [36]:
inflacion_final = inflacion_ecuador.T

inflacion_final.head()

            66
1960  1.676599
1961  3.985621
1962  2.870885
1963  5.939509
1964  4.034205

LIMPIEZA DE DESEMPLEO

In [37]:
desempleo = pd.read_csv(
    "../data/raw/API_SL.UEM.TOTL.ZS_DS2_es_csv_v2_7203.csv",
    skiprows=4
)

print("Desempleo cargado correctamente")

Desempleo cargado correctamente

In [38]:
desempleo_ecuador = desempleo[desempleo["Country Code"] == "ECU"]

desempleo_ecuador

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
66,Ecuador,ECU,"Desempleo, total (% de la fuerza laboral total...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.836,3.53,3.812,6.116,4.504,3.713,3.51,3.453,3.308,NaN

In [39]:
desempleo_ecuador = desempleo_ecuador.drop(
    columns=["Country Name", "Country Code", "Indicator Name", "Indicator Code", "Unnamed: 70"],
    errors="ignore"
)

desempleo_ecuador

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.597,3.836,3.53,3.812,6.116,4.504,3.713,3.51,3.453,3.308

In [40]:
desempleo_final = desempleo_ecuador.T

desempleo_final.head()

      66
1960 NaN
1961 NaN
1962 NaN
1963 NaN
1964 NaN

In [41]:
desempleo_final = desempleo_final.reset_index()

desempleo_final.columns = ["Año", "Desempleo"]

desempleo_final.head()

    Año  Desempleo
0  1960        NaN
1  1961        NaN
2  1962        NaN
3  1963        NaN
4  1964        NaN

In [42]:
pib_final = pib_final.reset_index()
pib_final.columns = ["Año", "PIB"]

inflacion_final = inflacion_final.reset_index()
inflacion_final.columns = ["Año", "Inflacion"]

datos_final = pib_final.merge(
    inflacion_final,
    on="Año",
    how="inner"
)

datos_final.head()

    Año       PIB  Inflacion
0  1960       NaN   1.676599
1  1961  5.124415   3.985621
2  1962  4.919147   2.870885
3  1963  2.106368   5.939509
4  1964  7.407245   4.034205

In [43]:
datos_final = datos_final.merge(
    desempleo_final,
    on="Año",
    how="inner"
)

datos_final.head()

    Año       PIB  Inflacion  Desempleo
0  1960       NaN   1.676599        NaN
1  1961  5.124415   3.985621        NaN
2  1962  4.919147   2.870885        NaN
3  1963  2.106368   5.939509        NaN
4  1964  7.407245   4.034205        NaN

PREPARAR LAS VARIABLES

In [44]:
datos_final = datos_final.drop(
    columns=["Tasa_Interes"],
    errors="ignore"
)

datos_final.head()

    Año       PIB  Inflacion  Desempleo
0  1960       NaN   1.676599        NaN
1  1961  5.124415   3.985621        NaN
2  1962  4.919147   2.870885        NaN
3  1963  2.106368   5.939509        NaN
4  1964  7.407245   4.034205        NaN

In [45]:
datos_final = datos_final.sort_values("Año")

datos_final

     Año       PIB  Inflacion  Desempleo
0   1960       NaN   1.676599        NaN
1   1961  5.124415   3.985621        NaN
2   1962  4.919147   2.870885        NaN
3   1963  2.106368   5.939509        NaN
4   1964  7.407245   4.034205        NaN
..   ...       ...        ...        ...
61  2021  9.421893   0.133251      4.504
62  2022  5.868424   3.466170      3.713
63  2023  1.832841   2.215688      3.510
64  2024 -1.944090   1.547325      3.453
65  2025  3.725949   0.710469      3.308

[66 rows x 4 columns]

UNIR LAS BASES

In [46]:
datos_final["Año"] = pd.to_numeric(datos_final["Año"], errors="coerce")

In [47]:
datos_final.dtypes

Año            int64
PIB          float64
Inflacion    float64
Desempleo    float64
dtype: object

In [48]:
datos_final = datos_final[
    (datos_final["Año"] >= 2007) &
    (datos_final["Año"] <= 2024)
]

datos_final

     Año       PIB  Inflacion  Desempleo
47  2007  1.902429   2.276185      3.142
48  2008  6.564921   8.400096      3.917
49  2009  1.091013   5.159968      4.608
50  2010  4.029138   3.554377      4.088
51  2011  8.481477   4.474533      3.458
52  2012  5.783212   5.101722      3.235
53  2013  7.211237   2.721776      3.083
54  2014  4.226065   3.589220      3.480
55  2015  0.119692   3.966646      3.616
56  2016 -0.687954   1.728265      4.597
57  2017  5.970399   0.417336      3.836
58  2018  1.044295  -0.224103      3.530
59  2019  0.165404   0.266013      3.812
60  2020 -9.245096  -0.338872      6.116
61  2021  9.421893   0.133251      4.504
62  2022  5.868424   3.466170      3.713
63  2023  1.832841   2.215688      3.510
64  2024 -1.944090   1.547325      3.453

In [49]:
datos_final.to_csv(
    "../data/processed/base_VAR_Ecuador.csv",
    index=False
)

print("Base econométrica guardada correctamente")

Base econométrica guardada correctamente

In [50]:
import os

print("RAW:", os.listdir("../data/raw"))
print("PROCESSED:", os.listdir("../data/processed"))

RAW: ['API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_285.csv', 'API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_57.csv', 'API_SL.UEM.TOTL.ZS_DS2_es_csv_v2_7203.csv']
PROCESSED: ['API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_285.zip', 'API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_57.zip', 'API_SL.UEM.TOTL.ZS_DS2_es_csv_v2_7203 (1).zip', 'base_VAR_Ecuador.csv']