In [1]:
import pandas as pd
from statsmodels.tsa.stattools import adfuller

In [2]:
df = pd.read_csv("../data/processed/base_VAR_Ecuador.csv")

df.head()

    Año       PIB  Inflacion  Desempleo
0  2007  1.902429   2.276185      3.142
1  2008  6.564921   8.400096      3.917
2  2009  1.091013   5.159968      4.608
3  2010  4.029138   3.554377      4.088
4  2011  8.481477   4.474533      3.458

In [3]:
def prueba_adf(serie, nombre):
    resultado = adfuller(serie.dropna())

    print("=" * 50)
    print(f"Prueba Dickey-Fuller: {nombre}")
    print("=" * 50)

    print(f"ADF Statistic : {resultado[0]:.4f}")
    print(f"p-value       : {resultado[1]:.4f}")
    print(f"Número de rezagos : {resultado[2]}")
    print(f"Observaciones : {resultado[3]}")

    print("\nValores críticos:")
    for clave, valor in resultado[4].items():
        print(f"{clave}: {valor:.4f}")

    if resultado[1] < 0.05:
        print("\n✅ La serie es estacionaria.")
    else:
        print("\n❌ La serie NO es estacionaria.")

In [4]:
prueba_adf(df["PIB"], "PIB")

==================================================
Prueba Dickey-Fuller: PIB
==================================================
ADF Statistic : -2.4569
p-value       : 0.1263
Número de rezagos : 7
Observaciones : 10

Valores críticos:
1%: -4.3316
5%: -3.2330
10%: -2.7487

❌ La serie NO es estacionaria.

In [5]:
prueba_adf(df["Inflacion"], "Inflación")

==================================================
Prueba Dickey-Fuller: Inflación
==================================================
ADF Statistic : -3.4835
p-value       : 0.0084
Número de rezagos : 7
Observaciones : 10

Valores críticos:
1%: -4.3316
5%: -3.2330
10%: -2.7487

✅ La serie es estacionaria.

In [6]:
prueba_adf(df["Inflacion"], "Inflación")

==================================================
Prueba Dickey-Fuller: Inflación
==================================================
ADF Statistic : -3.4835
p-value       : 0.0084
Número de rezagos : 7
Observaciones : 10

Valores críticos:
1%: -4.3316
5%: -3.2330
10%: -2.7487

✅ La serie es estacionaria.

TRANSFORMAR EN ESTACIONARIDAD EL PIB

In [7]:
df["PIB_diff"] = df["PIB"].diff()

df[["Año", "PIB", "PIB_diff"]].head()

    Año       PIB  PIB_diff
0  2007  1.902429       NaN
1  2008  6.564921  4.662492
2  2009  1.091013 -5.473908
3  2010  4.029138  2.938125
4  2011  8.481477  4.452339

In [8]:
df_var = df.dropna().copy()

df_var.head()

    Año       PIB  Inflacion  Desempleo  PIB_diff
1  2008  6.564921   8.400096      3.917  4.662492
2  2009  1.091013   5.159968      4.608 -5.473908
3  2010  4.029138   3.554377      4.088  2.938125
4  2011  8.481477   4.474533      3.458  4.452339
5  2012  5.783212   5.101722      3.235 -2.698264

In [9]:
prueba_adf(df_var["PIB_diff"], "PIB en primera diferencia")

==================================================
Prueba Dickey-Fuller: PIB en primera diferencia
==================================================
ADF Statistic : -4.4444
p-value       : 0.0002
Número de rezagos : 2
Observaciones : 14

Valores críticos:
1%: -4.0120
5%: -3.1042
10%: -2.6910

✅ La serie es estacionaria.

PIB, INFLACION Y DESEMPLEO

In [10]:
import pandas as pd
from statsmodels.tsa.stattools import adfuller

variables = {
    "PIB": df["PIB"],
    "Inflacion": df["Inflacion"],
    "Desempleo": df["Desempleo"]
}

resultados = []

for nombre, serie in variables.items():

    adf = adfuller(serie.dropna())

    resultados.append({
        "Variable": nombre,
        "ADF": round(adf[0],3),
        "p-value": round(adf[1],4),
        "Rezagos": adf[2],
        "Observaciones": adf[3],
        "Estacionaria": "Sí" if adf[1] < 0.05 else "No"
    })

tabla_adf = pd.DataFrame(resultados)

tabla_adf

    Variable    ADF  p-value  Rezagos  Observaciones Estacionaria
0        PIB -2.457   0.1263        7             10           No
1  Inflacion -3.484   0.0084        7             10           Sí
2  Desempleo -2.977   0.0371        7             10           Sí